name: STM32F4 Build

on:
  push:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: mdnf1992/cpp-dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: ESP-IDF build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/opt/toolchains/arm-toolchain.cmake --no-warn-unused-cli -G "Unix Makefiles" ..
          make
